meta_product_name: "Rentease"
meta_title: "Rentease - La solution pour un dossier immobilier simple et sécurisé"
meta_description: "Blablabla pookie"
meta_image: "favicon-32x32.png" # should exist in `app/assets/images/` # required for Twitter Cards